#!/bin/bash

# 1st arg is the name of the command
# 2nd arg would be a module name
# subsequent args should be ignored
if [[ $# == 2 ]]; then
    SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    $SCRIPT_DIR/gs-find-modules $2
fi
