#!/bin/bash

## Description: Run behat tests in the web container (deletes artifacts first)
## Usage: behat
## Example: "ddev behat [options] [<module>] [<paths>]"
## ProjectTypes: silverstripe
## ExecRaw: true

# Delete old artifacts first (from opinionated directory)
[[ -n "$(ls .ddev-extra/artifacts/ 2>/dev/null)" ]] && rm -r .ddev-extra/artifacts/*;

# If no tags option was passed, default to "--tags=gsat"
# I typically only want to run a given test at a time, and this is my opinionated way of identifying it.
if [[ $* != *--tags* ]]; then
    set -- "--tags=gsat" "$@"
fi

echo 'Killing any old chromedriver instances';
DRIVER_PID=$(pgrep chromedriver)
if [ -n "$DRIVER_PID" ]; then
    kill -15 $DRIVER_PID > /dev/null
fi

# Run chromedriver and behat
$(chromedriver --log-path=.ddev-extra/artifacts/chromedriver.log --log-level=INFO > /dev/null 2>&1 &) && behat "$@"
EXIT_VALUE=$?

# flush because there's a weirdness sometimes
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
$SCRIPT_DIR/flush

exit $EXIT_VALUE
