#!/bin/bash

## Description: Shortcut for running Silverstripe `sake dev/build flush=1`
## Usage: devbuild
## Example: "ddev devbuild"
# Note that most of my "silverstripe" projects just use the "php" type so I have greater control over them
## ProjectTypes: silverstripe, php
## ExecRaw: false

sake dev/build flush=1
# Then flush for webserver - see https://github.com/silverstripe/silverstripe-framework/issues/11145
echo "Flushing for webserver"
curl "${DDEV_PRIMARY_URL}/dev?flush=1" -o /dev/null
