#!/bin/bash

## Description: Shortcut for running Silverstripe `sake dev flush=1`
## Usage: flush
## Example: "ddev flush"
## ProjectTypes: silverstripe
## ExecRaw: false

# Flush in CLI first
echo "Flushing CLI"
sake dev flush=1
# Then flush for webserver - see https://github.com/silverstripe/silverstripe-framework/issues/11145
echo "Flushing for webserver"
curl "${DDEV_PRIMARY_URL}/dev?flush=1" -o /dev/null
