#!/bin/bash

## Description: Shortcut for running Silverstripe `sake dev flush=1`
## Usage: flush
## Example: "ddev flush"
## ProjectTypes: silverstripe
## ExecRaw: false

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SS_VERSION=$($SCRIPT_DIR/.ss-version)

if [[ $SS_VERSION > 5 ]] then

    echo "Flushing"
    sake flush

else

    # Flush in CLI first
    echo "Flushing CLI"
    sake dev flush=1
    # Then flush for webserver - see https://github.com/silverstripe/silverstripe-framework/issues/11145
    echo "Flushing for webserver"
    curl "${DDEV_PRIMARY_URL}/dev?flush=1" -o /dev/null

fi
